services:
  exchequer-postgres:
    container_name: "exchequer-postgres"
    image: exchequer-postgres:0.0.7
    build: "postgres"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${MAIN_POSTGRES_PASSWORD:-exchequersgreat}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    restart: always
    volumes:
      - ${VOLUME_DIR:-/opt/exchequer/storage/volumes}/postgres:/var/lib/postgresql
      - ${VOLUME_DIR:-/opt/exchequer/storage/volumes}/postgres/data:/var/lib/postgresql/data

    networks:
      - exchequer
networks:
  exchequer:
    external: true
